---
- name: "Reboot instance"
  shell: reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: "Wait for instance to reboot"
  local_action:
    wait_for host={{ ansible_ssh_host }}
    state=started
    port=22
    timeout=600
